#!/bin/sh

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f2)


#if the theme is not dark then we need to switch to it
if [ $THEMEIS != "dark.css" ]; then
    SWITCHTO="-dark"
    ROSEPINE=""
    GTK_VAL=0
    QT_SCHEME="Breeze"
else
    SWITCHTO=""
    ROSEPINE="-dawn"
    GTK_VAL=1
    QT_SCHEME="BreezeDark"
fi

#set the waybar theme
ln -sf ~/.config/waybar/style/style$SWITCHTO.css ~/.config/waybar/style.css

# Change rofi theme
ln -sf ~/.config/rofi/style/style$SWITCHTO.rasi ~/.config/rofi/style.rasi

# Change theme of fastfetch
ln -sf ~/.config/fastfetch/style/style$SWITCHTO.jsonc ~/.config/fastfetch/config.jsonc

#set the xfce theme
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"

#set the GTK theme
gsettings set org.gnome.desktop.interface gtk-theme "rose-pine$ROSEPINE-gtk"
gsettings set org.gnome.desktop.interface icon-theme "rose-pine$ROSEPINE-gtk"

# Set GTK3 and GTK4 dark preference (for non-Gnome apps)
GTK3_CONF="$HOME/.config/gtk-3.0/settings.ini"
GTK4_CONF="$HOME/.config/gtk-4.0/settings.ini"
mkdir -p "$(dirname "$GTK3_CONF")" "$(dirname "$GTK4_CONF")"

sed -i '/gtk-application-prefer-dark-theme/d' "$GTK3_CONF" 2>/dev/null
sed -i '/gtk-application-prefer-dark-theme/d' "$GTK4_CONF" 2>/dev/null

echo -e "[Settings]\ngtk-application-prefer-dark-theme=$GTK_VAL" >> "$GTK3_CONF"
echo -e "[Settings]\ngtk-application-prefer-dark-theme=$GTK_VAL" >> "$GTK4_CONF"

# --------------------
# Set Qt (KDE) theme
KDE_GLOBALS="$HOME/.config/kdeglobals"
if [ -f "$KDE_GLOBALS" ]; then
    sed -i "s/^ColorScheme=.*/ColorScheme=$QT_SCHEME/" "$KDE_GLOBALS"
fi

#change the background image and be cool about it ;)
BG_PATH="$HOME/.config/hypr/wallpapers/wallpaper.jpg"
ln -sf ~/.config/hypr/wallpapers/themes/images$SWITCHTO/link "$BG_PATH"
magick ~/.config/hypr/wallpapers/wallpaper.jpg -resize 2300x1294\> -quality 85 ~/.config/rofi/wallpaper.jpg
cp ~/.config/rofi/wallpaper.jpg ~/.config/wlogout/wallpaper.jpg
magick ~/.config/wlogout/wallpaper.jpg -blur 0x8 ~/.config/wlogout/wallpaper.jpg

swww img "$BG_PATH" --transition-type any --transition-duration 2

#update the sddm image
ln -sf /usr/share/sddm/themes/sdt/Backgrounds/wallpaper$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

# Hyprlock theme
ln -sf ~/.config/hypr/hyprlock/hyprlock$SWITCHTO.conf ~/.config/hypr/hyprlock.conf

#restart the waybar
killall -SIGUSR2 waybar
